// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0iuc2etGjlFUaurcoDa3JM39qXwtiw_8',
    appId: '1:50799712566:web:353aef09c3663d00423b97',
    messagingSenderId: '50799712566',
    projectId: 'authpractice-9f2c5',
    authDomain: 'authpractice-9f2c5.firebaseapp.com',
    storageBucket: 'authpractice-9f2c5.firebasestorage.app',
    measurementId: 'G-KNTY5968RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPuRLMf8WelukWixvtDfniRtZ_o9X2_8k',
    appId: '1:50799712566:android:04a6839f4f352b6f423b97',
    messagingSenderId: '50799712566',
    projectId: 'authpractice-9f2c5',
    storageBucket: 'authpractice-9f2c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApS0JWM-xlcvl1iPTNsW4Nbey-VXM1AYw',
    appId: '1:50799712566:ios:5148d0e2fdaa0310423b97',
    messagingSenderId: '50799712566',
    projectId: 'authpractice-9f2c5',
    storageBucket: 'authpractice-9f2c5.firebasestorage.app',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApS0JWM-xlcvl1iPTNsW4Nbey-VXM1AYw',
    appId: '1:50799712566:ios:5148d0e2fdaa0310423b97',
    messagingSenderId: '50799712566',
    projectId: 'authpractice-9f2c5',
    storageBucket: 'authpractice-9f2c5.firebasestorage.app',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0iuc2etGjlFUaurcoDa3JM39qXwtiw_8',
    appId: '1:50799712566:web:2fd2c3b92060081e423b97',
    messagingSenderId: '50799712566',
    projectId: 'authpractice-9f2c5',
    authDomain: 'authpractice-9f2c5.firebaseapp.com',
    storageBucket: 'authpractice-9f2c5.firebasestorage.app',
    measurementId: 'G-TQWJ3NF88N',
  );
}
